import React, { useRef } from "react";
import ReactMarkdown from "react-markdown";
import { useReactToPrint } from "react-to-print";
import { Printer } from "lucide-react";

const FinancialReport = ({ reportContent }) => {
  const componentRef = useRef(null);

  const handlePrint = useReactToPrint({
    contentRef: componentRef,
    documentTitle: "Financial_Plan_Report",
  });

  return (
    <div className="max-w-4xl mx-auto">
      {/* --- PRINT STYLES (This fixes the margins & text) --- */}
      <style>
        {`
          @media print {
            /* 1. Set Proper Margins on the Paper */
            @page {
              margin: 20mm;
              size: auto;
            }

            /* 2. Ensure Text is Black & Selectable */
            body {
              -webkit-print-color-adjust: exact;
              print-color-adjust: exact;
              color: black !important;
            }

            /* 3. Hide URL/Footer artifacts if browser adds them */
            /* Note: Some browsers force this, but this helps */
            
            /* 4. Remove shadows that might cause "Rasterization" (Image-look) */
            .print-clean {
              box-shadow: none !important;
              border: none !important;
              padding: 0 !important;
              margin: 0 !important;
            }
          }
        `}
      </style>

      {/* Print Button */}
      <div className="flex justify-end mb-4 print:hidden">
        <button
          onClick={() => handlePrint()}
          className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition font-medium shadow-sm"
        >
          <Printer size={18} />
          Download PDF
        </button>
      </div>

      {/* Report Container */}
      <div 
        ref={componentRef} 
        className="bg-white p-12 rounded-xl shadow-lg border border-gray-100 print-clean"
      >
        {/* Title */}
        <div className="mb-6 border-b pb-4">
          <h2 className="text-3xl font-bold text-gray-800 flex items-center gap-2">
            📊 AI Financial Analysis
          </h2>
          <p className="text-gray-500 text-sm mt-1">Generated by Autonomous Finance Agent</p>
        </div>

        {/* The Markdown Content */}
        <div className="markdown-content text-gray-700 leading-relaxed text-lg text-justify">
          <ReactMarkdown
            components={{
              h3: ({ node, ...props }) => (
                <h3 className="text-2xl font-bold text-blue-800 mt-8 mb-4 border-l-4 border-blue-600 pl-3 break-after-avoid" {...props} />
              ),
              strong: ({ node, ...props }) => (
                <strong className="font-bold text-gray-900 bg-yellow-100 px-1 rounded print:bg-transparent print:border-b-2 print:border-gray-800" {...props} />
              ),
              ul: ({ node, ...props }) => (
                <ul className="list-disc list-inside space-y-2 mb-4 pl-4" {...props} />
              ),
              li: ({ node, ...props }) => (
                <li className="text-gray-700 mb-2" {...props} />
              ),
              p: ({ node, ...props }) => (
                <p className="mb-4" {...props} />
              ),
              hr: ({ node, ...props }) => (
                <hr className="my-8 border-t-2 border-gray-100" {...props} />
              ),
            }}
          >
            {reportContent}
          </ReactMarkdown>
        </div>
        
        {/* Footer for the PDF */}
        <div className="mt-10 pt-6 border-t border-gray-100 text-center text-gray-400 text-sm hidden print:block">
           <p>This report is AI-generated for informational purposes only.</p>
        </div>
      </div>
    </div>
  );
};

export default FinancialReport;